# Generated by Django 3.0.6 on 2020-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='books_borrowed',
            field=models.ManyToManyField(blank=True, to='library2.Books'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='library2.Genre'),
        ),
    ]
